# Generated by Django 4.0.1 on 2022-10-06 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='last_request',
            field=models.DateTimeField(null=True),
        ),
    ]
